import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <nav>
        <h1>logo</h1>
        <ul>
          <li>
            <a href="#">About</a>
          </li>
        </ul>
      </nav>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
